name: Build Dreitier
 
on:
  workflow_dispatch:
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: set up settings.xml
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "snapshots", "url": "http://3.236.186.210:8081/artifactory/libs-snapshot" }]'
        plugin_repositories: '[{ "id": "snapshots", "url": "http://3.236.186.210:8081/artifactory/libs-snapshot" }]'
        servers: '[{ "id": "snapshots", "username": "${ARTIFACTORY_USERNAME_REF}", "password": "${ARTIFACTORY_TOKEN_REF}" }]'
    
 
    - name: Build with Maven
      env:
        ARTIFACTORY_USERNAME_REF: ${{ARTIFACTORY_USERNAME}}
        ARTIFACTORY_TOKEN_REF: ${{ secrets.ARTIFACTORY_TOKEN }}
      run: mvn -B package
      
