name: aws-connect

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
 
  workflow_dispatch:
    inputs:
      filename:
        default: repo.json
        required: true
        description: please provide json filename
jobs:
  aws-serv-conn:
    name: deploy-sftp
   
    runs-on: [ubuntu-latest]
    env:
      DIR: repositories
    steps:
      - name: download artifact
        uses: actions/checkout@v2
        
      - name: sftp-deploy
        run: |
           printf "%s" "${{env.ssh_private_key}}" >> ${{env.mykey}}
           chmod 600 ${{env.mykey}}
           #sftp -o StrictHostKeyChecking=no -i ${{env.mykey}} ec2-user@44.202.70.126
           echo 'sftp start'
           
           printf "%s" "put -r repositories /home/ec2-user" >${{env.temp_sftp_file}}
           sftp -b ${{env.temp_sftp_file}} -o StrictHostKeyChecking=no -i ${{env.mykey}} ec2-user@44.202.70.126
           ls
           put pom.xml 
        env:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          mykey: ../private_key.pem
          temp_sftp_file: ../sftp
     
